<a href="https://colab.research.google.com/github/TonyLiu836/NBA_MVP_Predictor/blob/main/NBA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nba_api
!pip install requests

Requirement already satisfied: nba_api in c:\users\leon\anaconda3\lib\site-packages (1.1.11)
Requirement already satisfied: requests in c:\users\leon\anaconda3\lib\site-packages (from nba_api) (2.25.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\leon\anaconda3\lib\site-packages (from requests->nba_api) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\leon\anaconda3\lib\site-packages (from requests->nba_api) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\leon\anaconda3\lib\site-packages (from requests->nba_api) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\leon\anaconda3\lib\site-packages (from requests->nba_api) (2020.12.5)
Requirement already satisfied: requests in c:\users\leon\anaconda3\lib\site-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\leon\anaconda3\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\leon\anaconda3\lib\site-packages (from requests) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\leon\anaconda3\lib\site-packages (from requests) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\leon\anaconda3\lib\site-packages (from requests) (4.0.0)

In [2]:
import pandas as pd

In [7]:
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.static import players
nba_players = players.get_players()

lebron = [p for p in nba_players if p['full_name'] == 'LeBron James'][0]
print(lebron)
career = playercareerstats.PlayerCareerStats(player_id=lebron['id'])
career.get_data_frames()[0]

{'id': 2544, 'full_name': 'LeBron James', 'first_name': 'LeBron', 'last_name': 'James', 'is_active': True}

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,...,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,...,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,30,30,1106.0,326,...,0.769,34,189,223,198,50,34,97,70,872

In [10]:
from nba_api.stats.endpoints import playerdashboardbyyearoveryear

player_info = playerdashboardbyyearoveryear.PlayerDashboardByYearOverYear(player_id=lebron['id'], per_mode_detailed='PerGame')
player_df = player_info.get_data_frames()[1]
player_df.loc[:, ['GROUP_VALUE', 'PTS', 'REB', 'AST', 'PLUS_MINUS']]

   GROUP_VALUE   PTS  REB   AST  PLUS_MINUS
0      2021-22  29.1  7.4   6.6         0.5
1      2020-21  25.0  7.7   7.8         6.4
2      2019-20  25.3  7.8  10.2         6.6
3      2018-19  27.4  8.5   8.3         2.1
4      2017-18  27.5  8.6   9.1         1.3
5      2016-17  26.4  8.6   8.7         6.5
6      2015-16  25.3  7.4   6.8         8.1
7      2014-15  25.3  6.0   7.4         7.8
8      2013-14  27.1  6.9   6.3         5.3
9      2012-13  26.8  8.0   7.3         9.5
10     2011-12  27.1  7.9   6.2         7.6
11     2010-11  26.7  7.5   7.0         7.8
12     2009-10  29.7  7.3   8.6         8.6
13     2008-09  28.4  7.6   7.2        10.8
14     2007-08  30.0  7.9   7.2         1.8
15     2006-07  27.3  6.7   6.0         4.8
16     2005-06  31.4  7.0   6.6         3.5
17     2004-05  27.2  7.4   7.2         1.9
18     2003-04  20.9  5.5   5.9        -1.8

### Data Collection Steps:
- For each season:
    - Get players who played in that season
    - For each player:
        - Query API for player stats and add to dataframe
    - Normalize data

In [20]:
from nba_api.stats.endpoints import teamplayerdashboard
from nba_api.stats.endpoints import leaguedashteamstats

# Get list of teams that played in a season
leagueteams = leaguedashteamstats.LeagueDashTeamStats(season='2020-21')
teams = leagueteams.get_data_frames()[0]
team_list = teams.loc[:, ['TEAM_ID','TEAM_NAME']]
print(team_list)

# Get list of players that played in a season
warriors_id = teams.at[9, 'TEAM_ID']
teamplayers = teamplayerdashboard.TeamPlayerDashboard(warriors_id, season='2020-21')
players = teamplayers.get_data_frames()[1]
good_players = players[players.loc[:,'MIN'] > 800]
players_list = good_players.loc[:, ['PLAYER_ID', 'PLAYER_NAME']]
print(players_list)

       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
    PLAYER_ID            PLAYER_NAME
1      203952         Andrew Wiggins
3     1627814             Damion Lee
4      203110         Draymond Green
7     1630164          James Wiseman
9     1629673           Jordan Poole
10    1629308  Juan Toscano-Anderson
11    1626162        Kelly Oubre Jr.
12     203145          Kent Bazemore
13    1626172           Kevon Looney
17     201939          Stephen Curry

In [13]:
players[1]

,GROUP_SET,PLAYER_ID,PLAYER_NAME,NICKNAME,GP,W,L,W_PCT,MIN,FGM,...,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK
0,Players,1629346,Alen Smailagic,Alen,15,10,5,0.667,83.855000,11,...,16,14,4,4,15,15,14,15,7,2
1,Players,203952,Andrew Wiggins,Andrew,71,38,33,0.535,2364.270000,505,...,4,1,16,17,2,2,10,2,4,2
2,Players,202954,Brad Wanamaker,Brad,39,20,19,0.513,625.140000,61,...,8,13,14,6,10,13,12,13,7,2
3,Players,1627814,Damion Lee,Damion,57,28,29,0.491,1079.000000,128,...,7,10,5,10,9,9,7,10,7,2
4,Players,203110,Draymond Green,Draymond,63,35,28,0.556,1981.761667,170,...,1,2,11,18,4,7,2,3,1,1
5,Players,1629672,Eric Paschall,Eric,40,20,20,0.500,695.016667,148,...,12,12,15,8,7,8,16,11,7,2
6,Players,1627780,Gary Payton II,Gary,10,7,3,0.700,40.411667,10,...,15,17,1,3,15,16,9,16,7,2
7,Players,1630164,James Wiseman,James,39,18,21,0.462,835.880000,191,...,14,4,13,13,8,6,17,9,4,2
8,Players,1628395,Jordan Bell,Jordan,1,1,0,1.000,14.686667,0,...,17,15,1,1,18,18,11,18,7,2
9,Players,1629673,Jordan Poole,Jordan,51,28,23,0.549,987.835000,205,...,8,9,12,9,5,4,8,7,7,2
10,Players,1629308,Juan Toscano-Anderson,Juan,53,28,25,0.528,1107.485000,121,...,6,6,8,11,12,11,5,6,7,2
11,Players,1626162,Kelly Oubre Jr.,Kelly,55,27,28,0.491,1687.550000,318,...,5,3,17,13,3,3,18,4,3,2
12,Players,203145,Kent Bazemore,Kent,67,35,32,0.522,1333.536667,176,...,3,5,9,16,6,5,3,5,6,2
13,Players,1626172,Kevon Looney,Kevon,61,34,27,0.557,1160.693333,108,...,10,7,9,15,11,12,4,8,7,2
14,Players,1627737,Marquese Chriss,Marquese,2,0,2,0.000,26.716667,5,...,17,15,3,2,17,17,13,17,7,2
15,Players,1628539,Mychal Mulder,Mychal,60,33,27,0.550,765.725000,119,...,12,8,6,7,14,10,6,12,7,2
16,Players,1630185,Nico Mannion,Nico,30,17,13,0.567,363.918333,39,...,11,17,7,5,13,14,15,14,7,2
17,Players,201939,Stephen Curry,Stephen,63,37,26,0.587,2151.518333,658,...,2,10,18,12,1,1,1,1,2,2

In [4]:
import pandas as pd
from nba_api.stats.endpoints import teamplayerdashboard
from nba_api.stats.endpoints import leaguedashteamstats

for start_year in range(1996, 2022):
    end_year = (start_year + 1) % 100
    print(f'{start_year}-{end_year:02}')
    leagueteams = leaguedashteamstats.LeagueDashTeamStats(season=f'{start_year}-{end_year:02}')
    teams = leagueteams.get_data_frames()[0]
    team_list = teams.loc[:, ['TEAM_ID','TEAM_NAME']]
    #print(team_list)

1996-97
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Hornets
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612748              Miami Heat
14  1610612749         Milwaukee Bucks
15  1610612750  Minnesota Timberwolves
16  1610612751         New Jersey Nets
17  1610612752         New York Knicks
18  1610612753           Orlando Magic
19  1610612755      Philadelphia 76ers
20  1610612756            Phoenix Suns
21  1610612757  Portland Trail Blazers
22  1610612758        Sacramento Kings
23  1610612759       San Antonio Spurs
24  1610612760     Seattle SuperSonics
25  1610612761         Toronto Raptors
26  1610612762               Utah Jazz
27  1610612763     Vancouver Grizzlies
28  1610612764      Washington Bullets
1997-98
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Hornets
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612748              Miami Heat
14  1610612749         Milwaukee Bucks
15  1610612750  Minnesota Timberwolves
16  1610612751         New Jersey Nets
17  1610612752         New York Knicks
18  1610612753           Orlando Magic
19  1610612755      Philadelphia 76ers
20  1610612756            Phoenix Suns
21  1610612757  Portland Trail Blazers
22  1610612758        Sacramento Kings
23  1610612759       San Antonio Spurs
24  1610612760     Seattle SuperSonics
25  1610612761         Toronto Raptors
26  1610612762               Utah Jazz
27  1610612763     Vancouver Grizzlies
28  1610612764      Washington Wizards
1998-99
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Hornets
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612748              Miami Heat
14  1610612749         Milwaukee Bucks
15  1610612750  Minnesota Timberwolves
16  1610612751         New Jersey Nets
17  1610612752         New York Knicks
18  1610612753           Orlando Magic
19  1610612755      Philadelphia 76ers
20  1610612756            Phoenix Suns
21  1610612757  Portland Trail Blazers
22  1610612758        Sacramento Kings
23  1610612759       San Antonio Spurs
24  1610612760     Seattle SuperSonics
25  1610612761         Toronto Raptors
26  1610612762               Utah Jazz
27  1610612763     Vancouver Grizzlies
28  1610612764      Washington Wizards
1999-00
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Hornets
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612748              Miami Heat
14  1610612749         Milwaukee Bucks
15  1610612750  Minnesota Timberwolves
16  1610612751         New Jersey Nets
17  1610612752         New York Knicks
18  1610612753           Orlando Magic
19  1610612755      Philadelphia 76ers
20  1610612756            Phoenix Suns
21  1610612757  Portland Trail Blazers
22  1610612758        Sacramento Kings
23  1610612759       San Antonio Spurs
24  1610612760     Seattle SuperSonics
25  1610612761         Toronto Raptors
26  1610612762               Utah Jazz
27  1610612763     Vancouver Grizzlies
28  1610612764      Washington Wizards
2000-01
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Hornets
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612748              Miami Heat
14  1610612749         Milwaukee Bucks
15  1610612750  Minnesota Timberwolves
16  1610612751         New Jersey Nets
17  1610612752         New York Knicks
18  1610612753           Orlando Magic
19  1610612755      Philadelphia 76ers
20  1610612756            Phoenix Suns
21  1610612757  Portland Trail Blazers
22  1610612758        Sacramento Kings
23  1610612759       San Antonio Spurs
24  1610612760     Seattle SuperSonics
25  1610612761         Toronto Raptors
26  1610612762               Utah Jazz
27  1610612763     Vancouver Grizzlies
28  1610612764      Washington Wizards
2001-02
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Hornets
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612763       Memphis Grizzlies
14  1610612748              Miami Heat
15  1610612749         Milwaukee Bucks
16  1610612750  Minnesota Timberwolves
17  1610612751         New Jersey Nets
18  1610612752         New York Knicks
19  1610612753           Orlando Magic
20  1610612755      Philadelphia 76ers
21  1610612756            Phoenix Suns
22  1610612757  Portland Trail Blazers
23  1610612758        Sacramento Kings
24  1610612759       San Antonio Spurs
25  1610612760     Seattle SuperSonics
26  1610612761         Toronto Raptors
27  1610612762               Utah Jazz
28  1610612764      Washington Wizards
2002-03
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612741           Chicago Bulls
3   1610612739     Cleveland Cavaliers
4   1610612742        Dallas Mavericks
5   1610612743          Denver Nuggets
6   1610612765         Detroit Pistons
7   1610612744   Golden State Warriors
8   1610612745         Houston Rockets
9   1610612754          Indiana Pacers
10  1610612746    Los Angeles Clippers
11  1610612747      Los Angeles Lakers
12  1610612763       Memphis Grizzlies
13  1610612748              Miami Heat
14  1610612749         Milwaukee Bucks
15  1610612750  Minnesota Timberwolves
16  1610612751         New Jersey Nets
17  1610612740     New Orleans Hornets
18  1610612752         New York Knicks
19  1610612753           Orlando Magic
20  1610612755      Philadelphia 76ers
21  1610612756            Phoenix Suns
22  1610612757  Portland Trail Blazers
23  1610612758        Sacramento Kings
24  1610612759       San Antonio Spurs
25  1610612760     Seattle SuperSonics
26  1610612761         Toronto Raptors
27  1610612762               Utah Jazz
28  1610612764      Washington Wizards
2003-04

       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612741           Chicago Bulls
3   1610612739     Cleveland Cavaliers
4   1610612742        Dallas Mavericks
5   1610612743          Denver Nuggets
6   1610612765         Detroit Pistons
7   1610612744   Golden State Warriors
8   1610612745         Houston Rockets
9   1610612754          Indiana Pacers
10  1610612746    Los Angeles Clippers
11  1610612747      Los Angeles Lakers
12  1610612763       Memphis Grizzlies
13  1610612748              Miami Heat
14  1610612749         Milwaukee Bucks
15  1610612750  Minnesota Timberwolves
16  1610612751         New Jersey Nets
17  1610612740     New Orleans Hornets
18  1610612752         New York Knicks
19  1610612753           Orlando Magic
20  1610612755      Philadelphia 76ers
21  1610612756            Phoenix Suns
22  1610612757  Portland Trail Blazers
23  1610612758        Sacramento Kings
24  1610612759       San Antonio Spurs
25  1610612760     Seattle SuperSonics
26  1610612761         Toronto Raptors
27  1610612762               Utah Jazz
28  1610612764      Washington Wizards
2004-05
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Bobcats
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612763       Memphis Grizzlies
14  1610612748              Miami Heat
15  1610612749         Milwaukee Bucks
16  1610612750  Minnesota Timberwolves
17  1610612751         New Jersey Nets
18  1610612740     New Orleans Hornets
19  1610612752         New York Knicks
20  1610612753           Orlando Magic
21  1610612755      Philadelphia 76ers
22  1610612756            Phoenix Suns
23  1610612757  Portland Trail Blazers
24  1610612758        Sacramento Kings
25  1610612759       San Antonio Spurs
26  1610612760     Seattle SuperSonics
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2005-06
       TEAM_ID                          TEAM_NAME
0   1610612737                      Atlanta Hawks
1   1610612738                     Boston Celtics
2   1610612766                  Charlotte Bobcats
3   1610612741                      Chicago Bulls
4   1610612739                Cleveland Cavaliers
5   1610612742                   Dallas Mavericks
6   1610612743                     Denver Nuggets
7   1610612765                    Detroit Pistons
8   1610612744              Golden State Warriors
9   1610612745                    Houston Rockets
10  1610612754                     Indiana Pacers
11  1610612746               Los Angeles Clippers
12  1610612747                 Los Angeles Lakers
13  1610612763                  Memphis Grizzlies
14  1610612748                         Miami Heat
15  1610612749                    Milwaukee Bucks
16  1610612750             Minnesota Timberwolves
17  1610612751                    New Jersey Nets
18  1610612740  New Orleans/Oklahoma City Hornets
19  1610612752                    New York Knicks
20  1610612753                      Orlando Magic
21  1610612755                 Philadelphia 76ers
22  1610612756                       Phoenix Suns
23  1610612757             Portland Trail Blazers
24  1610612758                   Sacramento Kings
25  1610612759                  San Antonio Spurs
26  1610612760                Seattle SuperSonics
27  1610612761                    Toronto Raptors
28  1610612762                          Utah Jazz
29  1610612764                 Washington Wizards
2006-07
       TEAM_ID                          TEAM_NAME
0   1610612737                      Atlanta Hawks
1   1610612738                     Boston Celtics
2   1610612766                  Charlotte Bobcats
3   1610612741                      Chicago Bulls
4   1610612739                Cleveland Cavaliers
5   1610612742                   Dallas Mavericks
6   1610612743                     Denver Nuggets
7   1610612765                    Detroit Pistons
8   1610612744              Golden State Warriors
9   1610612745                    Houston Rockets
10  1610612754                     Indiana Pacers
11  1610612746               Los Angeles Clippers
12  1610612747                 Los Angeles Lakers
13  1610612763                  Memphis Grizzlies
14  1610612748                         Miami Heat
15  1610612749                    Milwaukee Bucks
16  1610612750             Minnesota Timberwolves
17  1610612751                    New Jersey Nets
18  1610612740  New Orleans/Oklahoma City Hornets
19  1610612752                    New York Knicks
20  1610612753                      Orlando Magic
21  1610612755                 Philadelphia 76ers
22  1610612756                       Phoenix Suns
23  1610612757             Portland Trail Blazers
24  1610612758                   Sacramento Kings
25  1610612759                  San Antonio Spurs
26  1610612760                Seattle SuperSonics
27  1610612761                    Toronto Raptors
28  1610612762                          Utah Jazz
29  1610612764                 Washington Wizards
2007-08
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Bobcats
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612763       Memphis Grizzlies
14  1610612748              Miami Heat
15  1610612749         Milwaukee Bucks
16  1610612750  Minnesota Timberwolves
17  1610612751         New Jersey Nets
18  1610612740     New Orleans Hornets
19  1610612752         New York Knicks
20  1610612753           Orlando Magic
21  1610612755      Philadelphia 76ers
22  1610612756            Phoenix Suns
23  1610612757  Portland Trail Blazers
24  1610612758        Sacramento Kings
25  1610612759       San Antonio Spurs
26  1610612760     Seattle SuperSonics
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2008-09
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Bobcats
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612763       Memphis Grizzlies
14  1610612748              Miami Heat
15  1610612749         Milwaukee Bucks
16  1610612750  Minnesota Timberwolves
17  1610612751         New Jersey Nets
18  1610612740     New Orleans Hornets
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2009-10
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Bobcats
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612763       Memphis Grizzlies
14  1610612748              Miami Heat
15  1610612749         Milwaukee Bucks
16  1610612750  Minnesota Timberwolves
17  1610612751         New Jersey Nets
18  1610612740     New Orleans Hornets
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2010-11

       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Bobcats
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612763       Memphis Grizzlies
14  1610612748              Miami Heat
15  1610612749         Milwaukee Bucks
16  1610612750  Minnesota Timberwolves
17  1610612751         New Jersey Nets
18  1610612740     New Orleans Hornets
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2011-12
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612766       Charlotte Bobcats
3   1610612741           Chicago Bulls
4   1610612739     Cleveland Cavaliers
5   1610612742        Dallas Mavericks
6   1610612743          Denver Nuggets
7   1610612765         Detroit Pistons
8   1610612744   Golden State Warriors
9   1610612745         Houston Rockets
10  1610612754          Indiana Pacers
11  1610612746    Los Angeles Clippers
12  1610612747      Los Angeles Lakers
13  1610612763       Memphis Grizzlies
14  1610612748              Miami Heat
15  1610612749         Milwaukee Bucks
16  1610612750  Minnesota Timberwolves
17  1610612751         New Jersey Nets
18  1610612740     New Orleans Hornets
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2012-13
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Bobcats
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746    Los Angeles Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740     New Orleans Hornets
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2013-14
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Bobcats
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746    Los Angeles Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2014-15
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746    Los Angeles Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2015-16
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2016-17
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2017-18

       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2018-19
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2019-20
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2020-21
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards
2021-22
       TEAM_ID               TEAM_NAME
0   1610612737           Atlanta Hawks
1   1610612738          Boston Celtics
2   1610612751           Brooklyn Nets
3   1610612766       Charlotte Hornets
4   1610612741           Chicago Bulls
5   1610612739     Cleveland Cavaliers
6   1610612742        Dallas Mavericks
7   1610612743          Denver Nuggets
8   1610612765         Detroit Pistons
9   1610612744   Golden State Warriors
10  1610612745         Houston Rockets
11  1610612754          Indiana Pacers
12  1610612746             LA Clippers
13  1610612747      Los Angeles Lakers
14  1610612763       Memphis Grizzlies
15  1610612748              Miami Heat
16  1610612749         Milwaukee Bucks
17  1610612750  Minnesota Timberwolves
18  1610612740    New Orleans Pelicans
19  1610612752         New York Knicks
20  1610612760   Oklahoma City Thunder
21  1610612753           Orlando Magic
22  1610612755      Philadelphia 76ers
23  1610612756            Phoenix Suns
24  1610612757  Portland Trail Blazers
25  1610612758        Sacramento Kings
26  1610612759       San Antonio Spurs
27  1610612761         Toronto Raptors
28  1610612762               Utah Jazz
29  1610612764      Washington Wizards